version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_SOURCE: "postgresql://postgres:rocks@postgres:5432/simple_bank?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: bitnami/postgresql:15.4.0
    container_name: postgresql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=rocks
      - POSTGRESQL_DATABASE=simple_bank
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

