version: "3"
vars:
  DB_URL: "postgresql://postgres:rocks@localhost:5432/simple_bank?sslmode=disable"

tasks:
  default:
    desc: "Gettings started"
    cmds:
      - task: rmpostgres
      - task: postgres
      - sleep 5
      - task: createdb
      - task: migrateup
      - task: sqlc
      - task: tests

  postgres:
    desc: "Start postgres container"
    cmds:
      - docker run -d --name pgbank -e POSTGRESQL_PASSWORD=rocks -e POSTGRESQL_DATABASE=simple_bank -p 5432:5432 bitnami/postgresql:15.4.0

  rmpostgres:
    desc: "Delete postgres container"
    ignore_error: true
    cmds:
      - docker stop pgbank
      - docker rm -v pgbank

  db_schema:
    desc: "Generate db schema from dbml"
    cmds:
      - docker run --rm -v $(pwd)/doc:/app gitea.linuxcode.net/linuxcode/dbml-cli:latest dbml2sql --postgres -o schema.sql db.dbml

  sqlc:
    desc: "Generate go sql files"
    cmds:
      - docker run --rm -v $(pwd):/src -w /src sqlc/sqlc generate

  tests:
    desc: "Run tests with coverage"
    cmds:
      - go test -v -cover ./...

  migrateup:
    desc: "Migrate schema up"
    cmds:
      - migrate -path db/migration -database "{{.DB_URL}}" -verbose up

  migrateup1:
    desc: "Migrate schema up"
    cmds:
      - migrate -path db/migration -database "{{.DB_URL}}" -verbose up 1

  migratedown:
    desc: "Migrate schema down"
    cmds:
      - migrate -path db/migration -database "{{.DB_URL}}" -verbose down

  migratedown1:
    desc: "Migrate schema down"
    cmds:
      - migrate -path db/migration -database "{{.DB_URL}}" -verbose down 1

  server:
    desc: "Run the server"
    cmds:
      - go run main.go

  mock:
    desc: "Generate mock interface"
    cmds:
      - mockgen -package mockdb -destination db/mock/store.go github.com/fayca121/simplebank/db/sqlc Store

  proto:
    desc: "Generate go sources from proto files"
    cmds:
      - rm -f pb/*.go
      - rm -f doc/swagger/*.json
      - rm -f doc/statik/*.*
      - |
        protoc --proto_path=proto \
        --go_out=pb --go_opt=paths=source_relative --go-grpc_out=pb \
        --go-grpc_opt=paths=source_relative --grpc-gateway_out=pb \
        --grpc-gateway_opt paths=source_relative \
        --openapiv2_out=doc/swagger \
        --openapiv2_opt=allow_merge=true,merge_file_name=simple_bank \
        proto/*.proto
      - statik -src=./doc/swagger -dest=./doc

  evans:
    desc: "Launch avans cli client"
    cmds:
      - evans --host localhost --port 9090 -r repl
