version: "3"
vars:
  DB_URL: "postgresql://postgres:rocks@localhost:5432/simple_bank?sslmode=disable"

tasks:
  default:
    desc: "Gettings started"
    cmds:
      - task: rmpostgres
      - task: postgres
      - timeout 5
      - task: createdb
      - task: migrateup
      - task: sqlc
      - task: tests

  postgres:
    desc: "Start postgres container"
    cmds:
      - docker run -d --name pgbank -e POSTGRESQL_PASSWORD=rocks -p 5432:5432 bitnami/postgresql:15.4.0

  rmpostgres:
    desc: "Delete postgres container"
    ignore_error: true
    cmds:
      - docker stop pgbank
      - docker rm -v pgbank

  createdb:
    desc: "Create simple_bank database"
    cmds:
      - docker exec -it pgbank createdb --username=postgres --owner=postgres simple_bank

  dropdb:
    desc: "Drop simple_bank database"
    cmds:
      - docker exec -it pgbank dropdb --username=postgres simple_bank

  sqlc:
    desc: "Generate go sql files"
    cmds:
      - docker run --rm -v $(pwd):/src -w /src sqlc/sqlc generate

  tests:
    desc: "Run tests with coverage"
    cmds:
      - go test -v -cover ./...

  migrateup:
    desc: "Migrate schema up"
    cmds:
      - migrate -path db/migration -database "{{.DB_URL}}" -verbose up

  migratedown:
    desc: "Migrate schema down"
    cmds:
      - migrate -path db/migration -database "{{.DB_URL}}" -verbose down

  server:
    desc: "Run the server"
    cmds:
      - go run main.go
